### ISSUE TITLE
<Message>The specified key does not exist.</Message>

### ISSUE THREAD

**Issue by 4m1r** [melsicon/melsicon.de#49]
### **Type of Issue**

- [x] Bug
- [ ] Enhancement
- [ ] Documentation
- [ ] Maintenance
- [ ] Question

*New feature/enhancement: [name]

#### Priority

- [ ] Low
- [x] Medium
- [ ] High
- [ ] Critical

## **Description**
Web site breaks with message, The specified key does not exist.

## **Steps to reproduce**
From impressum page, if one visits external link from the website e.g. css Frankfurt and press back we get an error

<Message>The specified key does not exist.</Message>

## **Your Environment (if relevant)**

- Browser Name and Version:
- Operating System and Version (Desktop/Mobile):

**Comment by vicbergquist** [comment]
Thank you for submitting this issue!
I fixed it through CloudFront, so it should be OK now.
